import { BeatConfig } from '../types/beat';

export const beatConfig: BeatConfig = {
  beats: [
    {
      id: '1',
      title: 'Floater',
      audioUrl: '/beats/floater.wav',
      tags: ['hip-hop', 'trap', 'chill', "floaty"],
      bpm: 140,
      key: 'Dm',
      price: 0,
      downloadUrl: '/downloads/floater.wav',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Night Drive',
      audioUrl: '/beats/night-drive.wav',
      tags: ['synthwave', 'electronic', 'retro'],
      bpm: 120,
      key: 'Am',
      price: 9.99,
      downloadUrl: '/downloads/night-drive.wav',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'Urban Dreams',
      audioUrl: '/beats/urban-dreams.wav',
      tags: ['r&b', 'soul', 'chill'],
      bpm: 90,
      key: 'Fm',
      price: 14.99,
      downloadUrl: '/downloads/urban-dreams.wav',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'Digital Rain',
      audioUrl: '/beats/digital-rain.wav',
      tags: ['electronic', 'ambient', 'experimental'],
      bpm: 110,
      key: 'Em',
      price: 12.99,
      downloadUrl: '/downloads/digital-rain.wav',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Street Lights',
      audioUrl: '/beats/street-lights.wav',
      tags: ['hip-hop', 'boombap', 'classic'],
      bpm: 85,
      key: 'Bm',
      price: 19.99,
      downloadUrl: '/downloads/street-lights.wav',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ],
}; 